ccflags-y += -Idrivers/media/platform/msm/nubiacamera
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/common
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
