ccflags-y += -Idrivers/media/platform/msm/nubiacamera
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/isp/
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/io
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/common
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
