ccflags-y += -Idrivers/media/platform/msm/nubiacamera
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/common
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/camera
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/io
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/cci
obj-$(CONFIG_NUBIA_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ LC898123/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
