ccflags-y += -Idrivers/media/platform/msm/nubiacamera/
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/common
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/cci
obj-$(CONFIG_NUBIA_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
