ccflags-y += -Idrivers/media/platform/msm/nubiacamera
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/common
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/io
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/cci
obj-$(CONFIG_NUBIA_CAMERA) += FlsCmd.o md5.o OisCmd.c OisInter.o
