ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/nubiacamera
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/common
ccflags-y += -Idrivers/media/platform/msm/nubiacamera/sensor/io
obj-$(CONFIG_NUBIA_CAMERA) += msm_flash.o
